    - name: Update all packages
      community.general.zypper:
        name: '*'
        state: latest
  
    - name: Install git
      community.general.zypper:
        name: "git"
        state: present

    - name: Download cuda rpm
      ansible.builtin.get_url:
        url: "{{  opensuse_cuda_installer  }}"
        dest: "{{  opensuse_home_dir  }}"

    - name: Install rpm for cuda into zypper
      community.general.zypper:
        name: "cuda.rpm"
        disable_gpg_check: true
        state: present

    - name: Install cuda-toolkit
      community.general.zypper:
        name: "{{  opensuse_cuda_package  }}"
        update_cache: true
        disable_gpg_check: true
        state: present

    - name: Install nvidia drivers
      community.general.zypper:
        name: "{{  opensuse_nvidia_drivers  }}"
        state: present

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true