    - name: Install docker
      community.general.zypper:
        name: docker
        update_cache: true
        state: present
    - name: Install pip3
      community.general.zypper:
        name: python3-pip
        update_cache: true
        state: present
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true
    - name: "Starting docker service"
      service:
        name: "docker"
        state: started
        enabled: yes
