#################################################
# DO Community Playbooks: Docker
#################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Check for supported OS version
      fail:
        msg: "OS must be openSUSE or Ubuntu"
      when: (ansible_distribution|lower != 'opensuse leap' and
              ansible_distribution|lower != 'ubuntu')
    - name: Install supported OS
      include_role:
        name: "{{ DISTRO }}"

    - include_tasks: tasks/docker_setup.yml


      # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        env: "{{ env_list }}"
        image: "{{ default_container_image }}"
        published_ports: "{{ ports }}"
        restart_policy: "{{ restart_policy }}"
        privileged: "{{ privileged }}"
        state: started
      # This will check if there  is rancher to be installed
      when: rancher
      with_sequence: count={{ create_containers }}
