- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
  when: ubuntu_version == "focal" or DISTRO == "opensuse"

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - python3-docker
    state: latest
    update_cache: true
  when: ubuntu_version == "jammy"

- name: Create docker group
  ansible.builtin.group:
    name: "docker"
    state: present

- name: Adding user {{ USER }} to docker group
  ansible.builtin.user:
    name: "{{ USER }}"
    groups: "docker"
    append: "yes"

- name: Pull Rancher Docker image
  community.docker.docker_image:
    name: "{{ default_container_image }}"
    source: pull
    force_source: true
  when: rancher
