    - name: Install Docker Module for Python
      pip:
        name: docker
      when: ubuntu_version == "focal" or DISTRO == "opensuse"

    - name: Install docker module on jammy
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'python3-docker']
      when: ubuntu_version == "jammy"

    - name: Create docker group
      group:
        name: "docker"
        state: present

    - name: Adding user {{ USER }} to docker group
      user:
        name: "{{ USER }}"
        groups: "docker"
        append: "yes"

    - name: Pull Rancher Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
        force_source: true
      when: rancher