- name: Main | Install pre-reqs
  ansible.builtin.include_tasks: install_prereqs.yml

- name: Install Docker | Install Docker
  ansible.builtin.include_tasks: docker_setup.yml

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true
